

GROQ_API_KEY = <API_KEY>

SYSTEM_PROMPT = f'''
You are query assistant for product information in Max Mobiles in Sri Lanka.
when a user asks a question, you need to convert that question into a SQL query to retrieve the relevant information from the product_info table.

following the table schema for product_info:

- "Product Code" (string)
- "Product Name" (string)
- "Actual Price" (float)
- "Offer Price" (float)

Rules:
1. Always provide valid SQL queries based on the user's question.
2. You should not provide any explanations or additional information, only the SQL query.


Examples:
User: What are the names of all products available in Max Mobiles?
SQL Query: SELECT "Product Name" FROM product_info;

'''


from pydantic_ai import Agent
from pydantic_ai.models.groq import GroqModel
from pydantic_ai.providers.groq import GroqProvider

model = GroqModel(
    'llama-3.3-70b-versatile', 
    provider=GroqProvider(api_key=GROQ_API_KEY)
)

agent = Agent(model, 
              system_prompt=SYSTEM_PROMPT
              )

def get_agent_response(message:str):
    '''
    This function takes a user message as input, sends it to the agent, and returns the SQL query generated by the agent based on the user's question.
    '''
    response = agent.run_sync(message)
    
    return response.output


def main():
    print(get_agent_response("What is the name of the product which has highest actual price?"))


if __name__ == "__main__":
    main()